  MODULE('SCHOOL002.CLW')
BrowseCourses          PROCEDURE                      !Browse the Courses File
BrowseEnrollment       PROCEDURE                      !Browse the Enrollment File
UpdateTeachers         PROCEDURE                      !Update the Teachers File
SelectMajors           PROCEDURE                      !Select a Majors Record
UpdateMajors           PROCEDURE                      !Update the Majors File
UpdateStudents         PROCEDURE                      !Update the Students File
BrowseMajors           PROCEDURE                      !Browse the Majors File
BrowseStudents         PROCEDURE                      !Browse the Students File
StudentTree            PROCEDURE
BrowseTeachers         PROCEDURE                      !Browse the Teachers File
  END
