  MODULE('SCHOOL001.CLW')
SelectClasses          PROCEDURE                      !Select a Classes Record
UpdateEnrollment       PROCEDURE                      !Update the Enrollment File
SelectStudents         PROCEDURE                      !Select a Students Record
UpdateClasses          PROCEDURE                      !Update the Classes File
SelectCourses          PROCEDURE                      !Select a Courses Record
SelectTeachers         PROCEDURE                      !Select a Teachers Record
UpdateCourses          PROCEDURE                      !Update the Courses File
ClassTree              PROCEDURE
BrowseClasses          PROCEDURE                      !Browse the Classes File
  END
