  MODULE('SCHOOL003.CLW')
UpdateGrades           PROCEDURE
CourseEnrollment       PROCEDURE
AttendanceSheets       PROCEDURE
ClassSchedules1        PROCEDURE                      !Student Schedules
EnrollSummary          PROCEDURE
FinalGrades            PROCEDURE
StudentIDs             PROCEDURE
ClassSchedules2        PROCEDURE                      !Teacher Schedules
SplashIt               PROCEDURE
  END
